const UI_LANG_KEY = 'portiq_ui_language';

export const SUPPORTED_UI_LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'Hindi' },
  { code: 'mr', label: 'Marathi' },
  { code: 'gu', label: 'Gujarati' },
  { code: 'es', label: 'Spanish' },
  { code: 'fr', label: 'French' },
  { code: 'de', label: 'German' },
  { code: 'ru', label: 'Russian' },
  { code: 'zh', label: 'Chinese (Simplified)' },
  { code: 'ja', label: 'Japanese' },
];

export function getUiLanguage() {
  if (typeof window === 'undefined') return 'en';
  return window.localStorage.getItem(UI_LANG_KEY) || 'en';
}

export function setUiLanguage(code) {
  if (typeof window === 'undefined') return;
  window.localStorage.setItem(UI_LANG_KEY, code || 'en');
}

const STRINGS = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.meetings': 'Meetings',
    'nav.participantBook': 'Participant book',
    'nav.tasks': 'Tasks',
    'nav.insights': 'Insights',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'settings.subtitle': 'Manage your account settings and preferences.',
    'settings.menu': 'Menu',
    'settings.tabAccount': 'Account',
    'settings.tabPassword': 'Password',
    'settings.tabSubscription': 'Subscription',
    'settings.tabWorkspace': 'Workspace',
    'settings.tabDisplay': 'Display',
    'settings.tabNotifications': 'Notifications',
    'settings.tabGeneral': 'General',
    'settings.accountTagline': 'Account details for this workspace.',
    'settings.accountDetailsTitle': 'Account details',
    'settings.accountDetailsDesc': 'Your sign-in identity as stored for this admin account.',
    'settings.labelUser': 'User',
    'settings.labelEmail': 'Email',
    'settings.passwordTitle': 'Password',
    'settings.passwordDesc': 'Update the password you use to sign in.',
    'settings.currentPassword': 'Current password',
    'settings.currentPasswordPh': 'Enter current password',
    'settings.newPassword': 'New password',
    'settings.newPasswordPh': 'Enter new password',
    'settings.confirmPassword': 'Confirm new password',
    'settings.confirmPasswordPh': 'Re-enter new password',
    'settings.updating': 'Updating…',
    'settings.changePassword': 'Change password',
    'settings.subscriptionTitle': 'Subscription',
    'settings.subscriptionDesc': 'Your product, plan, and billing status.',
    'settings.labelProduct': 'Product',
    'settings.labelStatus': 'Status',
    'settings.statusComplimentary': 'Complimentary',
    'settings.statusActive': 'Active',
    'settings.statusInactive': 'Inactive',
    'settings.manageSubscription': 'Manage subscription',
    'settings.cancelSubscription': 'Cancel subscription',
    'settings.cancelling': 'Cancelling…',
    'settings.workspaceTitle': 'Participant book',
    'settings.workspaceDesc': 'Manage saved people for meeting invitations and voice enrollment.',
    'settings.openParticipantBook': 'Open participant book',
    'settings.themeTitle': 'Theme',
    'settings.themeDesc': 'Choose light or dark appearance for the dashboard.',
    'settings.themeLight': 'Light',
    'settings.themeDark': 'Dark',
    'settings.languageTitle': 'Dashboard language',
    'settings.languageDesc': 'Language used for navigation labels and headings.',
    'settings.languageHint':
      'Changes navigation labels and headings. Content and email addresses remain as entered.',
    'settings.notificationsTitle': 'Notifications',
    'settings.notificationsDesc': 'Email preferences for this account.',
    'settings.notifyEmail': 'Email notifications',
    'settings.notifySummary': 'Summary reminders',
    'settings.generalCompanyTitle': 'Company name',
    'settings.generalCompanyDesc': 'Shown in meeting defaults where applicable.',
    'settings.companyPh': 'Your Company',
    'settings.generalDurationTitle': 'Default meeting duration',
    'settings.generalDurationDesc': 'Suggested duration in minutes for new meetings.',
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.meetings': 'मीटिंग्स',
    'nav.participantBook': 'प्रतिभागी पुस्तक',
    'nav.tasks': 'कार्य',
    'nav.insights': 'इनसाइट्स',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.admin': 'एडमिन',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'लॉगआउट',
  },
  mr: {
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.meetings': 'मीटिंग्स',
    'nav.participantBook': 'सहभागी पुस्तिका',
    'nav.tasks': 'कार्ये',
    'nav.insights': 'इनसाइट्स',
    'nav.profile': 'प्रोफाइल',
    'nav.admin': 'अ‍ॅडमिन',
    'nav.settings': 'सेटिंग्ज',
    'nav.logout': 'लॉगआउट',
  },
  gu: {
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.meetings': 'મીટિંગ્સ',
    'nav.participantBook': 'ભાગ લેનાર પુસ્તક',
    'nav.tasks': 'કાર્યો',
    'nav.insights': 'ઇન્સાઇટ્સ',
    'nav.profile': 'પ્રોફાઇલ',
    'nav.admin': 'એડમિન',
    'nav.settings': 'સેટિંગ્સ',
    'nav.logout': 'લોગ આઉટ',
  },
  es: {
    'nav.dashboard': 'Panel',
    'nav.meetings': 'Reuniones',
    'nav.participantBook': 'Libreta de participantes',
    'nav.tasks': 'Tareas',
    'nav.insights': 'Insights',
    'nav.profile': 'Perfil',
    'nav.admin': 'Admin',
    'nav.settings': 'Ajustes',
    'nav.logout': 'Cerrar sesión',
  },
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.meetings': 'Réunions',
    'nav.participantBook': 'Carnet de participants',
    'nav.tasks': 'Tâches',
    'nav.insights': 'Insights',
    'nav.profile': 'Profil',
    'nav.admin': 'Admin',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Déconnexion',
  },
  de: {
    'nav.dashboard': 'Dashboard',
    'nav.meetings': 'Meetings',
    'nav.participantBook': 'Teilnehmerbuch',
    'nav.tasks': 'Aufgaben',
    'nav.insights': 'Insights',
    'nav.profile': 'Profil',
    'nav.admin': 'Admin',
    'nav.settings': 'Einstellungen',
    'nav.logout': 'Abmelden',
  },
  ru: {
    'nav.dashboard': 'Панель',
    'nav.meetings': 'Встречи',
    'nav.participantBook': 'Книга участников',
    'nav.tasks': 'Задачи',
    'nav.insights': 'Аналитика',
    'nav.profile': 'Профиль',
    'nav.admin': 'Админ',
    'nav.settings': 'Настройки',
    'nav.logout': 'Выйти',
  },
  zh: {
    'nav.dashboard': '仪表盘',
    'nav.meetings': '会议',
    'nav.participantBook': '参会人名册',
    'nav.tasks': '任务',
    'nav.insights': '洞察',
    'nav.profile': '个人资料',
    'nav.admin': '管理',
    'nav.settings': '设置',
    'nav.logout': '退出登录',
  },
  ja: {
    'nav.dashboard': 'ダッシュボード',
    'nav.meetings': 'ミーティング',
    'nav.participantBook': '参加者ブック',
    'nav.tasks': 'タスク',
    'nav.insights': 'インサイト',
    'nav.profile': 'プロフィール',
    'nav.admin': '管理',
    'nav.settings': '設定',
    'nav.logout': 'ログアウト',
  },
};

export function L(key) {
  const lang = getUiLanguage();
  const table = STRINGS[lang] || STRINGS.en;
  return table[key] || STRINGS.en[key] || key;
}

